### ISSUE TITLE
Hyperparameters of the results from paper

### ISSUE THREAD

**Issue by zknus** [twitter-research/neural-sheaf-diffusion#3]
Hi team,

May I know the hyperparameter you used for each dataset？ I'm trying to reproduce the results from your paper. But in some dataset (Cornell), the results I got is far from the results shown in Table 1 of your paper. Can I have the hyperparameter you used for table 1?   Thanks!!

**Comment by crisbodnar** [comment]
Hi @zknus ,

I have added training scripts in `exp/scripts/` for the other heterophilic datasets, which should yield results that are similar to what we report in the paper. I will now close this issue but feel free to reopen it if you have further questions or comments.
